/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#5e605b',
        'on-surface': '#31332f',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e3e3dc',
        surface: '#fcf9f6',
        'surface-container': '#efeee9',
        'primary-fixed': '#caebc8',
        'surface-container-low': '#f5f3ef',
        'on-primary-fixed': '#29462d',
        'inverse-surface': '#0e0e0d',
        'on-background': '#31332f',
        'inverse-primary': '#dbfdd9',
        primary: '#48654a',
        'on-secondary-container': '#6f4a25',
        'surface-dim': '#dadbd3',
        'outline-variant': '#b2b2ac',
        'surface-variant': '#e3e3dc',
        'on-error': '#fff7f6',
        'on-secondary': '#fff7f4',
        'on-primary-container': '#3c583e',
        'tertiary-container': '#dbfce4',
        'primary-fixed-dim': '#bcddbb',
        'surface-container-high': '#e9e8e2',
        'primary-dim': '#3c593f',
        outline: '#7a7b76',
        'secondary-fixed-dim': '#ffca9b',
        'on-tertiary-fixed': '#34503e',
        'tertiary-dim': '#3d5947',
        'on-primary': '#e4ffe1',
        'secondary-fixed': '#ffdcbf',
        'secondary-container': '#ffdcbf',
        'primary-container': '#caebc8',
        'on-error-container': '#742410',
        secondary: '#7e5731',
        'on-tertiary-container': '#466250',
        'error-container': '#fe8b70',
        tertiary: '#496553',
        'surface-tint': '#48654a',
        'secondary-dim': '#704b26',
        'surface-bright': '#fcf9f6',
        background: '#fcf9f6',
        'inverse-on-surface': '#9e9d9a',
        'on-primary-fixed-variant': '#456247',
        error: '#9e422c',
        'on-tertiary': '#e7ffec',
      },
      fontFamily: {
        display: ['Lora', 'Noto Serif SC', 'Songti SC', 'STSong', 'serif'],
        headline: ['Manrope', 'Plus Jakarta Sans', 'PingFang SC', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'PingFang SC', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        soft: '0 2px 8px rgba(49, 51, 47, 0.04)',
        lift: '0 12px 32px -8px rgba(49, 51, 47, 0.12)',
        glow: '0 8px 32px rgba(72, 101, 74, 0.18)',
        'glow-soft': '0 4px 24px rgba(72, 101, 74, 0.10)',
      },
      animation: {
        'fade-in': 'fadeIn 600ms ease both',
        'slide-up': 'slideUp 500ms cubic-bezier(0.22, 1, 0.36, 1) both',
        'scale-in': 'scaleIn 400ms cubic-bezier(0.22, 1, 0.36, 1) both',
        float: 'float 6s ease-in-out infinite',
        breathe: 'breathe 8s ease-in-out infinite',
        'pulse-soft': 'pulseSoft 2.4s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.96)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        breathe: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.5' },
          '50%': { transform: 'scale(1.15)', opacity: '0.9' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.45' },
        },
      },
    },
  },
  plugins: [],
}
