/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#5e605b',
        'on-surface': '#31332f',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e3e3dc',
        surface: '#fcf9f6',
        'surface-container': '#efeee9',
        'primary-fixed': '#caebc8',
        'surface-container-low': '#f5f3ef',
        'on-primary-fixed': '#29462d',
        'inverse-surface': '#0e0e0d',
        'on-background': '#31332f',
        'inverse-primary': '#dbfdd9',
        primary: '#48654a',
        'on-secondary-container': '#6f4a25',
        'surface-dim': '#dadbd3',
        'outline-variant': '#b2b2ac',
        'surface-variant': '#e3e3dc',
        'on-error': '#fff7f6',
        'on-secondary': '#fff7f4',
        'on-primary-container': '#3c583e',
        'tertiary-container': '#dbfce4',
        'primary-fixed-dim': '#bcddbb',
        'surface-container-high': '#e9e8e2',
        'primary-dim': '#3c593f',
        outline: '#7a7b76',
        'secondary-fixed-dim': '#ffca9b',
        'on-tertiary-fixed': '#34503e',
        'tertiary-dim': '#3d5947',
        'on-primary': '#e4ffe1',
        'secondary-fixed': '#ffdcbf',
        'secondary-container': '#ffdcbf',
        'primary-container': '#caebc8',
        'on-error-container': '#742410',
        secondary: '#7e5731',
        'on-tertiary-container': '#466250',
        'error-container': '#fe8b70',
        tertiary: '#496553',
        'surface-tint': '#48654a',
        'secondary-dim': '#704b26',
        'surface-bright': '#fcf9f6',
        background: '#fcf9f6',
        'inverse-on-surface': '#9e9d9a',
        'on-primary-fixed-variant': '#456247',
        error: '#9e422c',
        'on-tertiary': '#e7ffec',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'PingFang SC', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}